[tox]
requires = tox-uv>=1
envlist = py312-django{42,52},quality,translations

[pycodestyle]
exclude = .git,.tox

[pytest]
# Use the workbench settings file.
DJANGO_SETTINGS_MODULE = workbench.settings
addopts = --cov-report term-missing --cov-report xml
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning

[testenv]
runner = uv-venv-lock-runner
allowlist_externals =
    make
    mkdir
dependency_groups =
    django42: django42
    django52: test
commands =
    mkdir -p var
    pytest {posargs:tests/unit/ --cov drag_and_drop_v2}

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups =
    quality
commands =
    pycodestyle drag_and_drop_v2 tests manage.py --max-line-length=120
    pylint drag_and_drop_v2
    pylint tests --rcfile=tests/pylintrc

[testenv:translations]
runner = uv-venv-lock-runner
allowlist_externals =
    make
dependency_groups =
    django42
commands =
    make check_translations_up_to_date
