name: Python CI

on:
  pull_request:
    branches:
      - '**'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        toxenv: [django42, django52, quality, translations]

    name: ${{ matrix.toxenv }}

    steps:
    - name: checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: recursive

    - name: setup uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: "${{ matrix.python-version }}"
        enable-cache: true

    - name: Install translations dependencies
      if: ${{ startsWith(matrix.toxenv, 'translations') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext

    - name: Install CI dependencies
      run: uv sync --group ci

    - name: Run Tests
      run: uv run tox -e ${{ matrix.toxenv }}
